Fix usage of `dumper` and `dump` in the documents
dlang-community/D-YAML pull request #285
Opened 2022-03-03 14:10 UTC by tom-tan

Current documents uses `dumper` function that takes an output range but the latest version of D-YAML (v0.8.5) only provides `dumper` with no arguments (See https://dyaml.dpldocs.info/v0.8.5/dyaml.dumper.dumper.html).

This request fixes `getting_started.md` and `custom_types.md` to use the latest interface of `dumper` and `Dumper.dump`.

2022-03-03 21:28 UTC, Herringway commented
Whoops! I knew I was forgetting something...

2022-03-03 21:30 UTC, Herringway requested changes

2022-03-03 21:30 UTC, Herringway commented on docs/tutorials/getting_started.md
> +documents. *dumper()* returns a *Dumpper* with the default setting.
Typo here. Should be Dumper.

2022-03-04 02:08 UTC, Herringway approved these changes

2022-03-04 02:09 UTC, merged

2022-03-04 03:30 UTC, tom-tan commented
Thanks!